version: '2.1'
services:
  jenkins:
    image: "yuequan/jenkins"
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes: 
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_volume:
    driver: local