master:
  image: "jenkins/jenkins:lts"
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - ~/jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock